name: Linux builds
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  Linux_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build minimal
        run: |
          echo "timestamp=`date +%F-%T | sed -e 's/:/-/g' | sed -e 's/-//g'`" >> $GITHUB_ENV
          ./build --disable-freetype --disable-libfluidsynth --disable-mt32 --disable-screenshots
      - name: Install libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nasm fluidsynth libfluidsynth-dev libpcap-dev libslirp-dev libsdl-net1.2-dev libsdl2-net-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
          mkdir src/bin
      - name: Build Linux SDL1
        run: |
          top=`pwd`
          ./build-debug
          strip --strip-all $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl1
      - name: Build Linux SDL2
        run: |
          top=`pwd`
          ./build-debug-sdl2
          strip --strip-all $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl2
      - name: Unit testing
        run: |
          top=`pwd`
          $top/src/bin/dosbox-x-sdl1 -tests
          $top/src/bin/dosbox-x-sdl2 -tests
      - name: Upload release package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dosbox-x-linux-${{ env.timestamp }}
          path: ${{ github.workspace }}/src/bin/
