name: macOS builds
on: [push, pull_request]
#on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: DOSBox-X macOS
        run: |
          brew install autoconf automake nasm
          top=`pwd`
          mkdir $top/src/bin
          ./build-macosx
          strip $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl1
          ./build-macosx-sdl2
          strip $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl2
      - name: Upload release package
        uses: actions/upload-artifact@v2
        with:
          name: dosbox-x-macos
          path: ${{ github.workspace }}/src/bin/
