name: macOS builds
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  macOS_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Install libraries
        run: |
          echo "timestamp=`date +%F-%T | sed -e 's/:/-/g' | sed -e 's/-//g'`" >> $GITHUB_ENV
          brew install autoconf automake nasm glfw glew sdl_net sdl2_net
          mkdir -p src/bin/dosbox-x
          mkdir -p src/bin/dosbox-x-sdl2
          cd vs/sdlnet && ./build-dosbox.sh
      - name: Build macOS SDL1
        run: |
          top=`pwd`
          ./build-macos
          strip $top/src/dosbox-x
          make dosbox-x.app
          mv dosbox-x.app $top/src/bin/dosbox-x
          cp $top/CHANGELOG $top/src/bin/dosbox-x/CHANGELOG.txt
          cp $top/COPYING $top/src/bin/dosbox-x/COPYING.txt
          cp $top/contrib/macos/readme.txt $top/src/bin/dosbox-x/README.txt
      - name: Build macOS SDL2
        run: |
          top=`pwd`
          ./build-macos-sdl2
          strip $top/src/dosbox-x
          make dosbox-x.app
          rm dosbox-x.app/Contents/MacOS/libSDL2-2*.dylib
          mv dosbox-x.app $top/src/bin/dosbox-x-sdl2
          cp $top/CHANGELOG $top/src/bin/dosbox-x-sdl2/CHANGELOG.txt
          cp $top/COPYING $top/src/bin/dosbox-x-sdl2/COPYING.txt
          cp $top/contrib/macos/readme.txt $top/src/bin/dosbox-x-sdl2/README.txt
      - name: Unit testing
        run: |
          top=`pwd`
          chmod +x $top/src/bin/dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x $top/src/bin/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/dosbox-x
          $top/src/bin/dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x -tests
          $top/src/bin/dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/dosbox-x -tests
      - name: Upload preview package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dosbox-x-macosx-x86_64-${{ env.timestamp }}
          path: ${{ github.workspace }}/src/bin/
