name: macOS builds
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  macOS_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Install libraries
        run: |
          echo "timestamp=`date +%F-%T | sed -e 's/:/-/g' | sed -e 's/-//g'`" >> $GITHUB_ENV
          brew install autoconf automake nasm glfw glew sdl_net sdl2_net
          mkdir src/bin
          cd vs/sdlnet && ./build-dosbox.sh
      - name: Build macOS SDL2
        run: |
          top=`pwd`
          ./build-macosx-sdl2
          strip $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl2
      - name: Build macOS SDL1
        run: |
          top=`pwd`
          ./build-macosx
          strip $top/src/dosbox-x
          cp $top/src/dosbox-x $top/src/bin/dosbox-x-sdl1
      - name: Unit testing
        run: |
          top=`pwd`
          chmod +x $top/src/bin/dosbox-x-sdl1 $top/src/bin/dosbox-x-sdl2
          $top/src/bin/dosbox-x-sdl1 -tests
          $top/src/bin/dosbox-x-sdl2 -tests
      - name: Package build
        run: |
          top=`pwd`
          mkdir -p $top/src/bin/drivez
          mkdir -p $top/src/bin/glshaders
          mkdir -p $top/src/bin/languages
          cp $top/CHANGELOG $top/src/bin/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/src/bin/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/src/bin/dosbox-x.reference.full.conf
          cp $top/contrib/fonts/FREECG98.BMP $top/src/bin/FREECG98.BMP
          cp $top/contrib/fonts/wqy_1?pt.bdf $top/src/bin/
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/src/bin/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/src/bin/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/src/bin/drivez/readme.txt
          cp $top/contrib/glshaders/* $top/src/bin/glshaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/src/bin/languages/; done
      - name: Upload release package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dosbox-x-macos-${{ env.timestamp }}
          path: ${{ github.workspace }}/src/bin/
