name: 64-bit MinGW builds
on: [push, pull_request]
#on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libslirp mingw-w64-x86_64-libtool mingw-w64-x86_64-nasm autoconf automake
      - name: DOSBox-X MinGW64
        run: |
          top=`pwd`
          ln -s $top/build-scripts/mingw/make.exe /usr/bin/make.exe
          ./build-mingw
          strip --strip-all $top/src/dosbox-x.exe
          mkdir -p $top/package/mingw-build/mingw
          cp $top/src/dosbox-x.exe $top/package/mingw-build/mingw/dosbox-x.exe
          cp $top/CHANGELOG $top/package/mingw-build/mingw/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/mingw-build/mingw/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/mingw-build/mingw/dosbox-x.reference.full.conf
          ./build-mingw-sdl2
          strip --strip-all $top/src/dosbox-x.exe
          mkdir -p $top/package/mingw-build/mingw-sdl2
          cp $top/src/dosbox-x.exe $top/package/mingw-build/mingw-sdl2/dosbox-x.exe
          cp $top/CHANGELOG $top/package/mingw-build/mingw-sdl2/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/mingw-build/mingw-sdl2/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/mingw-build/mingw-sdl2/dosbox-x.reference.full.conf
      - name: Upload release package
        uses: actions/upload-artifact@v2
        with:
          name: dosbox-x-mingw64
          path: ${{ github.workspace }}/package/
