name: 32-bit Visual Studio builds
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  MSBuild32_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build Visual Studio Win32 SDL1
        shell: pwsh
        run: |
          msbuild -m vs/dosbox-x.sln -t:dosbox-x:Rebuild -p:Configuration=Release -p:Platform=Win32
      - name: Package Visual Studio Win32 SDL1
        shell: bash
        run: |
          top=`pwd`
          $top/bin/Win32/Release/dosbox-x.exe -tests -set waitonerror=false -set logfile=tests.log || (echo Unit test completed: failure && exit 1)
          cat tests.log
          mkdir -p $top/package/bin/Win32/Release/drivez
          mkdir -p $top/package/bin/Win32/Release/scripts
          mkdir -p $top/package/bin/Win32/Release/shaders
          mkdir -p $top/package/bin/Win32/Release/glshaders
          mkdir -p $top/package/bin/Win32/Release/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/bin/Win32/Release/dosbox-x.conf
          cp $top/bin/Win32/Release/dosbox-x.exe $top/package/bin/Win32/Release/dosbox-x.exe
          cp $top/CHANGELOG $top/package/bin/Win32/Release/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/bin/Win32/Release/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/bin/Win32/Release/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/bin/Win32/Release/README.txt
          cp $top/contrib/windows/installer/inpout32.dll $top/package/bin/Win32/Release/inpout32.dll
          cp $top/contrib/fonts/FREECG98.BMP $top/package/bin/Win32/Release/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/bin/Win32/Release/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/bin/Win32/Release/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/bin/Win32/Release/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/bin/Win32/Release/scripts/
          cp $top/contrib/windows/shaders/* $top/package/bin/Win32/Release/shaders/
          cp $top/contrib/glshaders/* $top/package/bin/Win32/Release/glshaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/bin/Win32/Release/languages/; done
      - name: Build Visual Studio Win32 SDL2
        shell: pwsh
        run: |
          msbuild -m vs/dosbox-x.sln -t:dosbox-x:Rebuild -p:Configuration="Release SDL2" -p:Platform=Win32
      - name: Package Visual Studio Win32 SDL2
        shell: bash
        run: |
          top=`pwd`
          $top/bin/Win32/"Release SDL2"/dosbox-x.exe -tests -set waitonerror=false -set logfile=tests.log || (echo Unit test completed: failure && exit 1)
          cat tests.log
          mkdir -p $top/package/bin/Win32/"Release SDL2"/drivez
          mkdir -p $top/package/bin/Win32/"Release SDL2"/scripts
          mkdir -p $top/package/bin/Win32/"Release SDL2"/shaders
          mkdir -p $top/package/bin/Win32/"Release SDL2"/glshaders
          mkdir -p $top/package/bin/Win32/"Release SDL2"/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/bin/Win32/"Release SDL2"/dosbox-x.conf
          cp $top/bin/Win32/"Release SDL2"/dosbox-x.exe $top/package/bin/Win32/"Release SDL2"/dosbox-x.exe
          cp $top/CHANGELOG $top/package/bin/Win32/"Release SDL2"/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/bin/Win32/"Release SDL2"/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/bin/Win32/"Release SDL2"/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/bin/Win32/"Release SDL2"/README.txt
          cp $top/contrib/windows/installer/inpout32.dll $top/package/bin/Win32/"Release SDL2"/inpout32.dll
          cp $top/contrib/fonts/FREECG98.BMP $top/package/bin/Win32/"Release SDL2"/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/bin/Win32/"Release SDL2"/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/bin/Win32/"Release SDL2"/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/bin/Win32/"Release SDL2"/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/bin/Win32/"Release SDL2"/scripts/
          cp $top/contrib/windows/shaders/* $top/package/bin/Win32/"Release SDL2"/shaders/
          cp $top/contrib/glshaders/* $top/package/bin/Win32/"Release SDL2"/glshaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/bin/Win32/"Release SDL2"/languages/; done
          cp $top/COPYING $top/package/COPYING
      - name: Upload release package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dosbox-x-vsbuild-win32
          path: ${{ github.workspace }}/package/

  MSBuild_ARM32_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build Visual Studio ARM32 SDL1
        shell: pwsh
        run: |
          msbuild -m vs/dosbox-x.sln -t:dosbox-x:Rebuild -p:Configuration=Release -p:Platform=ARM -p:PostBuildEventUseInBuild=false
      - name: Package Visual Studio ARM32 SDL1
        shell: bash
        run: |
          top=`pwd`
          mkdir -p $top/package/bin/ARM/Release/drivez
          mkdir -p $top/package/bin/ARM/Release/scripts
          mkdir -p $top/package/bin/ARM/Release/shaders
          mkdir -p $top/package/bin/ARM/Release/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/bin/ARM/Release/dosbox-x.conf
          cp $top/bin/ARM/Release/dosbox-x.exe $top/package/bin/ARM/Release/dosbox-x.exe
          cp $top/CHANGELOG $top/package/bin/ARM/Release/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/bin/ARM/Release/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/bin/ARM/Release/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/bin/ARM/Release/README.txt
          cp $top/contrib/fonts/FREECG98.BMP $top/package/bin/ARM/Release/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/bin/ARM/Release/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/bin/ARM/Release/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/bin/ARM/Release/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/bin/ARM/Release/scripts/
          cp $top/contrib/windows/shaders/* $top/package/bin/ARM/Release/shaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/bin/ARM/Release/languages/; done
      - name: Build Visual Studio ARM32 SDL2
        shell: pwsh
        run: |
          msbuild -m vs/dosbox-x.sln -t:dosbox-x:Rebuild -p:Configuration="Release SDL2" -p:Platform=ARM -p:PostBuildEventUseInBuild=false
      - name: Package Visual Studio ARM32 SDL2
        shell: bash
        run: |
          top=`pwd`
          mkdir -p $top/package/bin/ARM/"Release SDL2"/drivez
          mkdir -p $top/package/bin/ARM/"Release SDL2"/scripts
          mkdir -p $top/package/bin/ARM/"Release SDL2"/shaders
          mkdir -p $top/package/bin/ARM/"Release SDL2"/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/bin/ARM/"Release SDL2"/dosbox-x.conf
          cp $top/bin/ARM/"Release SDL2"/dosbox-x.exe $top/package/bin/ARM/"Release SDL2"/dosbox-x.exe
          cp $top/CHANGELOG $top/package/bin/ARM/"Release SDL2"/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/bin/ARM/"Release SDL2"/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/bin/ARM/"Release SDL2"/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/bin/ARM/"Release SDL2"/README.txt
          cp $top/contrib/fonts/FREECG98.BMP $top/package/bin/ARM/"Release SDL2"/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/bin/ARM/"Release SDL2"/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/bin/ARM/"Release SDL2"/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/bin/ARM/"Release SDL2"/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/bin/ARM/"Release SDL2"/scripts/
          cp $top/contrib/windows/shaders/* $top/package/bin/ARM/"Release SDL2"/shaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/bin/ARM/"Release SDL2"/languages/; done
          cp $top/COPYING $top/package/COPYING
      - name: Upload release package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dosbox-x-vsbuild-arm32
          path: ${{ github.workspace }}/package/
